disabled_rules:
- opening_brace
- force_cast
- force_try
- trailing_comma
- function_body_length

identifier_name:
    excluded:
    - vm
    - vc
    - id
    - x
    - y
    - z
    - i
        
    
